[[modules]]
  name = "overview"
  name_alias = "概述"

  [[modules.children]]
    name = "overview_host"
    name_alias = "主机概述"
    metric_names = ["host_info", "host_cpu_info", "host_disk_info", "host_disk_block_info", "host_bios_info", "host_memory_info", "host_network_info"]

  [[modules.children]]
    name = "overview_yasdb"
    name_alias = "数据库概述"
    metric_names = ["yasdb_instance", "yasdb_database", "yasdb_file_permission", "yasdb_listen_address"]

[[modules]]
  name = "host_check"
  name_alias = "主机检查"

  [[modules.children]]
    name = "host_workload_check"
    name_alias = "主机负载检查"
    metric_names = ["host_history_cpu_usage", "host_current_cpu_usage", "host_history_disk_io", "host_current_disk_io", "host_current_memory_usage", "host_history_memory_usage", "host_history_network_io", "host_current_network_io", "host_firewalld", "host_iptables"]

[[modules]]
  name = "yasdb_check"
  name_alias = "数据库检查"

  [[modules.children]]
    name = "yasdb_standby_check"
    name_alias = "主备检查"
    metric_names = ["yasdb_replication_status"]

  [[modules.children]]
    name = "yasdb_config_check"
    name_alias = "数据库配置检查"
    metric_names = ["yasdb_parameter", "yasdb_os_auth"]

  [[modules.children]]
    name = "yasdb_tablespace_check"
    name_alias = "表空间检查"
    metric_names = ["yasdb_tablespace", "yasdb_datafile"]

  [[modules.children]]
    name = "yasdb_controlfile_check"
    name_alias = "控制文件检查"
    metric_names = ["yasdb_controlfile", "yasdb_controlfile_count"]

  [[modules.children]]
    name = "yasdb_backup_check"
    name_alias = "备份检查"
    metric_names = []

  [[modules.children]]
    name = "yasdb_workload_check"
    name_alias = "负载检查"
    metric_names = ["yasdb_session"]

[[modules]]
  name = "object_check"
  name_alias = "对象检查"

  [[modules.children]]
    name = "object_number_count"
    name_alias = "对象数量统计"
    metric_names = ["yasdb_object_count", "yasdb_object_owner", "yasdb_object_tablespace"]

  [[modules.children]]
    name = "object_status_check"
    name_alias = "对象状态检查"
    metric_names = []

  [[modules.children]]
    name = "object_table_check"
    name_alias = "表"
    metric_names = []

  [[modules.children]]
    name = "object_constraint_check"
    name_alias = "约束"
    metric_names = []

  [[modules.children]]
    name = "object_index_check"
    name_alias = "索引"
    metric_names = ["yasdb_index_blevel", "yasdb_index_column", "yasdb_index_invisible","yasdb_index_oversized","yasdb_index_table_index_not_together"]

  [[modules.children]]
    name = "object_sequence_check"
    name_alias = "序列"
    metric_names = ["yasdb_sequence_no_available"]

  [[modules.children]]
    name = "object_task_check"
    name_alias = "任务"
    metric_names = ["yasdb_task_running"]

  [[modules.children]]
    name = "object_package_check"
    name_alias = "包"
    metric_names = ["yasdb_package_no_package_package_body"]

[[modules]]
  name = "security_check"
  name_alias = "安全检查"

  [[modules.children]]
    name = "security_login_config"
    name_alias = "登录检查"
    metric_names = ["yasdb_security_password_strength","yasdb_security_maximum_login_attempts"]

  [[modules.children]]
    name = "security_permission_check"
    name_alias = "用户与权限检查"
    metric_names = ["yasdb_security_user_no_open","yasdb_security_user_with_system_table_privileges","yasdb_security_user_with_dba_role","yasdb_security_user_all_privilege_or_system_privileges","yasdb_security_user_use_system_tablespace"]

  [[modules.children]]
    name = "security_audit_check"
    name_alias = "审计日志分析"
    metric_names = ["yasdb_security_audit_cleanup_task","yasdb_security_audit_file_size"]

[[modules]]
  name = "log_analysis"
  name_alias = "日志分析"

  [[modules.children]]
    name = "log_run_analysis"
    name_alias = "数据库变更"
    metric_names = ["yasdb_run_log_database_changes"]

  [[modules.children]]
    name = "log_redo_analysis"
    name_alias = "REDO日志分析"
    metric_names = ["yasdb_redo_log", "yasdb_redo_log_count"]

  [[modules.children]]
    name = "log_undo_analysis"
    name_alias = "UNDO日志分析"
    metric_names = ["yasdb_undo_size","yasdb_total_undo_block","yasdb_transactions"]

  [[modules.children]]
    name = "log_error_analysis"
    name_alias = "错误日志分析"
    metric_names = ["yasdb_run_log_error","yasdb_alert_log_error","host_dmesg_log_error","host_system_log_error"]

[[modules]]
  name = "custom_check"
  name_alias = "自定义检查"

  [[modules.children]]
    name = "custom_check_bash"
    name_alias = "自定义BASH指标"
    metric_names = []

  [[modules.children]]
    name = "custom_check_sql"
    name_alias = "自定义SQL指标"
    metric_names = []
