log_level = "DEBUG"
max_duration = "30d"
min_duration = "1m"
output = "./results"
range = "24h"
sql_timeout = 10
scrape_interval = 1
scrape_times = 30
metric_paths = ["./config/default_metric.toml", "./config/custom_metric.toml"]
default_module_path = "./config/report_module.toml"
