package constdef

const (
	YASDB_HOME        = "YASDB_HOME"
	YASDB_DATA        = "YASDB_DATA"
	YASDB_USER        = "YASDB_USER"
	YASDB_PASSWORD    = "YASDB_PASSWORD"
	YASDB_LISTEN_ADDR = "YASDB_LISTEN_ADDR"
)
